name: Testes de Unidade com CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Rodar os testes
      run: |
        python -m unittest test_valida_cpf.py
